[build]
  base = ""
  publish = "static"
  command = "python manage.py runserver"

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "agrosage.settings.production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200